'use client';
import { Button } from '@mui/material';
import styles from './page.module.scss';
import axios from 'axios';
import { useState } from 'react';

export default function Index() {
  const [data, setData] = useState([]);

  const fetchData = () => {
    axios
      .get('http://localhost:3333/api/users')
      .then((response) => {
        setData(response.data);
      })
      .catch((error) => {
        console.log('Error fetching data:', error);
      });
  };

  return (
    <div className={styles.page}>
      <h1>Welcome to fe!</h1>
      <p>Generated by create-nx-workspace</p>
      <Button onClick={fetchData} className={styles.button}>
        Click me
      </Button>
      <ul>
        {data?.map((user: any) => (
          <li key={user?._id}>
            {/*{user?.email}*/}
            {user?.name}
          </li>
        ))}
      </ul>
    </div>
  );
}
